Fix gcc warnings and clang build failures
* Fix python3 warning with gcc and build failure with clang

src/certificate.c:613:3: error: non-void function 'PyInit__certificate' should return a value [-Wreturn-type]
                return;
                ^
src/certificate.c:622:3: error: non-void function 'PyInit__certificate' should return a value [-Wreturn-type]
                return;

* Use g_error_new_literal() instead of g_error_new() when argument is not a format string

This fixes several warnings when compiling with clang that look like this:

/builddir/build/BUILD/subscription-manager-1.25.9/src/dnf-plugins/product-id/productdb.c:87:38: error: format string is not a string literal
 (potentially insecure) [-Werror,-Wformat-security]
        *err = g_error_new(quark, 0, error_string);
                                     ^~~~~~~~~~~~
/builddir/build/BUILD/subscription-manager-1.25.9/src/dnf-plugins/product-id/productdb.c:87:38: note: treat the string as an argument to avo
id this
        *err = g_error_new(quark, 0, error_string);
                                     ^
                                     "%s",