1207306: Revert DBus compliance status code.
Problematic in 7.1 and appearing again in 6.7, given the implementation is not
getting used yet and the feature needs a re-think, pulling this out for 6.7 as
well.

Revert "884285: Needs to maintain loop for dbus calls"

This reverts commit d38e4e58c709a45021307ffa60ae5926c09182b7.

Conflicts:
	src/subscription_manager/logutil.py

Revert "1159266: rhsm-icon -i fails with "TypeError: 'NoneType' object has no attribute '__getitem__'""

This reverts commit e3b6516ed3a7e1e382a38746bb2f7e1dc190679d.

Conflicts:
	src/daemons/rhsm_d.py

Revert "Send list of compliance reasons on dbus"

This reverts commit cedc122d3178f4853fc2135fc19457c8bf6fa475.

Remove some dbus testing no longer used.