Revert "884285: Needs to maintain loop for dbus calls"
This reverts commit 0c3134d8eb15c3893d0eebcde8a4dff2fbc8fd50.

Revert "1159266: rhsm-icon -i fails with "TypeError: 'NoneType' object has no attribute '__getitem__'""
This reverts commit e3b6516ed3a7e1e382a38746bb2f7e1dc190679d.

Conflicts:
	src/daemons/rhsm_d.py

Revert "Send list of compliance reasons on dbus"
This reverts commit cedc122d3178f4853fc2135fc19457c8bf6fa475.