Fix issue with getPoolsList
* Some changes introduced in this PR: #2197 have been lost
  during merging #2129 to master. This PR should fix this issue
* Running: subscription-manager list --available was terminated
  with following error:
  getPoolsList() got an unexpected keyword argument 'page'