1159266: rhsm-icon -i fails with "TypeError: 'NoneType' object has no attribute '__getitem__'"
Modified calls to move new status call out of startup process for rhsm-icon. The
poke no longer fires the full status response.
Updated to fit dbus expected standard for Properites