Fix failing tests
The 'certificate2.py' patch is required for 'test_productid.py'.
'test_update_installed_no_product_certs_with_active_with_enabled' fails
otherwise with

  File "src/rhsm/certificate2.py", line 503, in __eq__
    return self.serial == other.serial
 AttributeError: 'tuple' object has no attribute 'serial'

coming from mock.py stacktrace where it zips several objects. The test
works in different branches unchanged. The source for the code has not
changed, only test setups have been altered. Thus, it is safer to patch
the comparator than to ignore or disable the test.

(Adapted from b1f10df)